mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^pets/', include('pets.urls', namespace='pets')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^shelters/', include('shelters.urls', namespace='shelters')),
    url(r'^$', 'mysite.views.home', name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/news/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'news.views.show', name='show'),
    url(r'^(?P<id>[0-9]+)/$', 'news.views.details', name='details')
]

mysite/shelters/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'shelters.views.show', name='show'),
    url(r'^(?P<id>[0-9]+)/$', 'shelters.views.detail', name='detail'),
    url(r'^add/$', 'shelters.views.add', name='add')
]

mysite/shelters/models.py
from django.db import models

# Create your models here.


class Shelter(models.Model):
    name = models.CharField(max_length=10)
    photo = models.ImageField()
    description = models.CharField(max_length=4096)
    address = models.CharField(max_length=1024)

mysite/shelters/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render_to_response
from shelters.form import ShelterForm


def show(request):
    return render_to_response('shelters/show.html')


def detail(request, id):
    return render_to_response('shelters/detail.html')


def add(request):
    form = ShelterForm()
    if request.method == "POST":
        form = ShelterForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    return render_to_response('shelters/add.html')

mysite/shelters/templates/shelters/add.html
{% extends 'base.html' %}
{% block title %}
    Создание страницы приюта
{% endblock %}
{%  block body %}
{%for error in errors%}
    <p>{{ error }}</p>
{% endfor %}

<form method="post" action="{% url 'shelters:add' %}">
    {% csrf_token %}

    {{ form.as_p }}

    <input type="submit" value="Создать"/>
</form>
{%  endblock %}

mysite/shelters/templates/shelters/detail.html
{% extends 'base.html' %}
{% block title %}
    Приют
{% endblock %}
{% block body %}
    <div>

    </div>
{% endblock %}

mysite/shelters/templates/shelters/show.html
{% extends 'base.html' %}
{% block title %}
    Приюты
{% endblock %}
{% block body %}
    <div>

    </div>
{% endblock %}