mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^pets/', include('pets.urls', namespace='pets')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^shelters/', include('shelters.urls', namespace='shelters')),
    url(r'^$', 'mysite.views.home', name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/news/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'news.views.show', name='show'),
    url(r'^(?P<id>[0-9]+)/$', 'news.views.details', name='details')
]

mysite/pets/urls.py
from django.conf.urls import url
from pets.views import BreedsList

urlpatterns = [
    url(r'breeds^$', BreedsList.as_view()),
    url(r'^(?P<id>[0-9]+)/$', 'pets.views.show_pet', name='show'),
    url(r'^add/$', 'pets.views.add_pet', name='add')
]

mysite/pets/models.py
from django.db import models
from shelters.models import Shelter
from users.models import Profile

# Create your models here.


class TypeOfPet(models.Model):
    name = models.CharField(max_length=50)

    def __str__(self):
        return self.name


class Breed(models.Model):
    type = models.ForeignKey(TypeOfPet)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=4096)

    def __str__(self):
        return self.name


GENDER = (
    ('F', 'Female'),
    ('M', 'Male')
)


class Pet(models.Model):
    breed = models.ForeignKey(Breed)
    user = models.ForeignKey(Profile)
    photo = models.ImageField()
    shelter = models.ForeignKey(Shelter)
    nickname = models.CharField(max_length=50)
    birthday = models.DateField(blank=True, null=True)
    gender = models.CharField(max_length=1, choices=GENDER)

    def __str__(self):
        return self.breed.type.name+": "+self.nickname

mysite/pets/forms.py
from django.forms import ModelForm
from pets.models import Pet


class PetForm(ModelForm):
    class Meta:
        model = Pet
        fields = ['breed', 'nickname', 'birthday', 'gender', 'photo']

mysite/pets/views.py
# Create your views here.
from django.shortcuts import render_to_response
from django.views.generic import ListView
from pets.forms import PetForm
from pets.models import Breed


def show_pet(request, id):
    return render_to_response('pets/show_pet.html')


def add_pet(request):
    form = PetForm()
    if request.method == "POST":
        form = PetForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
    return render_to_response('pets/add_pet.html', {'form': form})


class BreedsList(ListView):
    template_name = "pets/breeds.html"

    def get_queryset(self):
        return Breed.objects.all()

mysite/pets/templates/pets/add_pet.html
{% extends 'base.html' %}
{% block title %}
    Добавить питомца
{% endblock %}
{% block body %}
    <div>
        {% for error in errors %}
            <p>{{ error }}</p>
        {% endfor %}

        <form method="post" action="{% url 'pets:add' %}">
            {% csrf_token %}

            {{ form.as_p }}

            <input type="submit" value="Добавить"/>
        </form>
    </div>
{% endblock %}

mysite/pets/templates/pets/breeds.html
{% extends 'base.html' %}
{% block title %}
    Породы
{% endblock %}
{% block body %}
    <div>

    </div>
{% endblock %}

mysite/pets/templates/pets/show_pet.html
{% extends 'base.html' %}
{% block title %}
    Питомец
{% endblock %}
{% block body %}
    <div>

    </div>
{% endblock %}