mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^pets/', include('pets.urls', namespace='pets')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^shelters/', include('shelters.urls', namespace='shelters')),
    url(r'^$', 'mysite.views.home', name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/news/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'news.views.show', name='show'),
    url(r'^(?P<id>[0-9]+)/$', 'news.views.details', name='details')
]

mysite/users/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^login$', 'users.views.login', name="login"),
    url(r'^logout$', 'users.views.logout', name="logout"),
    url(r'^registration$', 'users.views.register', name='registration'),
    url(r'^(?P<id>[0-9]+)$', 'users.views.profile', name='profile'),
    url(r'my$', 'users.views.my', name='my'),
]

mysite/users/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

GENDER = (
    ('F', 'Female'),
    ('M', 'Male')
)


# Create your models here.
class Profile(models.Model):
    photo = models.ImageField()
    user = models.OneToOneField(User)
    birthday = models.DateField(auto_now_add=True)
    gender = models.CharField(max_length=1, choices=GENDER)

    def __str__(self):
        return self.user.username

mysite/users/forms.py
# -*- coding: utf-8 -*-

import datetime
from django import forms


GENDER = (
    ('F', 'Female'),
    ('M', 'Male')
)


class LoginForm(forms.Form):
    login = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


class RegistrationForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label=u"Логин")
    email = forms.EmailField(widget=forms.EmailInput(attrs={'class': 'form-control'}), label=u"Email")
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label=u"Имя")
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label=u"Фамилия")
    photo = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}), label=u"Фотография")
    birthday = forms.DateField(initial=datetime.date.today, widget=forms.DateInput(attrs={'class': 'form-control'}), label=u"Дата рождения")
    gender = forms.ChoiceField(choices=GENDER, widget=forms.Select(attrs={'class': 'form-control'}), label=u"Пол")
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label=u"Пароль")
    rep_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label=u"Повтроите пароль")


class UpdateForm(forms.Form):
    first_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label=u"Имя")
    last_name = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}), label=u"Фамилия")
    photo = forms.ImageField(widget=forms.FileInput(attrs={'class': 'form-control'}), label=u"Фотография")
    birthday = forms.DateField(initial=datetime.date.today, widget=forms.DateInput(attrs={'class': 'form-control'}), label=u"Дата рождения")
    gender = forms.ChoiceField(choices=GENDER, widget=forms.Select(attrs={'class': 'form-control'}), label=u"Пол")
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label=u"Пароль")
    rep_password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}), label=u"Повтроите пароль")

mysite/users/views.py
# -*- coding: utf-8 -*-
from django.contrib.auth.models import User
from django.shortcuts import render
from users.forms import LoginForm, RegistrationForm, UpdateForm
from django.contrib.auth import authenticate, login as auth_login, logout as logout_user
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from models import Profile


# Create your views here.
def login(request):
    if request.user.is_authenticated():
        return HttpResponseRedirect(reverse("mysite.views.home"))
    else:
        if request.method == "POST":
            form = LoginForm(request.POST)
            if form.is_valid():
                user = authenticate(
                    username=form.cleaned_data["login"],
                    password=form.cleaned_data["password"]
                )
                if user is not None:
                    auth_login(request, user)
                    if "next" in request.GET:
                        return HttpResponseRedirect(request.GET["next"])
                    else:
                        return HttpResponseRedirect(reverse("mysite.views.home"))

            return render(request, "users/login.html", {"form": form})
        else:

            form = LoginForm()
            return render(request, "users/login.html", {"form": form})


@login_required(login_url="/users/login")
def logout(request):
    logout_user(request)
    if "next" in request.GET:
        return HttpResponseRedirect(request.GET["next"])
    else:
        return HttpResponseRedirect(reverse("users.views.my"))


def register(request):
    if request.method == "POST":
        form = RegistrationForm(request.POST)
        if form.is_valid():
            profile = Profile(
                user=User.objects.create_user(
                    username=form.cleaned_data["username"],
                    email=form.cleaned_data["email"],
                    password=form.cleaned_data["password"],
                    first_name=form.cleaned_data["first_name"],
                    last_name=form.cleaned_data["last_name"]
                ),
                photo=form.cleaned_data["photo"],
                birthday=form.cleaned_data["birthday"],
                gender=form.cleaned_data["gender"]
            ).save()
            return render(request, 'users/success.html')
        else:
            print(form.is_valid())
            return render(request, "users/registration.html", {"form": form})

    else:
        form = RegistrationForm()
        return render(request, "users/registration.html", {"form": form})


def profile(request, id):
    profile = Profile.objects.get(pk=id)
    isEdite = request.user.id == id
    return render(request, 'users/profile.html', {"profile": profile, "isEdite": isEdite})


@login_required(login_url="/users/login")
def my(request):
    if request.POST:
        form = UpdateForm(request.POST)
        if form.is_valid():
            profile = Profile(
                user=User.objects.create_user(
                    username=form.cleaned_data["username"],
                    email=form.cleaned_data["email"],
                    password=form.cleaned_data['password'],
                    first_name=form.cleaned_data["first_name"],
                    last_name=form.cleaned_data["last_name"]
                )
            ).save()
        return HttpResponseRedirect(reverse("my"))
    else:
        profile = Profile.objects.get(user=request.user)
        form = UpdateForm()
        form.fields['first_name'].initial = profile.user.first_name
        form.fields['last_name'].initial = profile.user.last_name
        form.fields['gender'].initial = profile.gender
        form.fields['birthday'].initial = profile.birthday
        return render(request, 'users/my_profile.html', {"profile": profile, "form":form})

mysite/users/templates/users/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Вход
{% endblock %}
{% block css %}
    <link href="{% static 'resources/css/sing_in.css' %}" rel="stylesheet">
{% endblock %}
{% block carousel %}
{% endblock %}
{% block body %}
    <div class="container">
        <form class="form-signup" role="form" action="{% url 'users:login' %}" method="post">
            {% csrf_token %}
            <h2 class="form-signin-heading">Пожалуйста войдите</h2>
            {% for error in errors %}
                <p>{{ error }}</p>
            {% endfor %}
            <input id="id_login" name="login" type="text" class="form-control" placeholder="Логин" required autofocus>
            <input id="id_password" name="password" type="password" class="form-control" placeholder="Пароль" required>
            <label class="checkbox">
                <input type="checkbox" value="remember-me"> Remember me
            </label>
            <input class="btn btn-lg btn-primary btn-block" type="submit" value="Вход"/>
            <a href="{% url 'users:registration' %}">Зарегистрироваться</a>
        </form>

    </div> <!-- /container -->
{% endblock %}

mysite/users/templates/users/my_profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Личный кабинет
{% endblock %}
{% block css %}
    <link href="{% static 'resources/css/profile.css' %}" rel="stylesheet">
{% endblock %}
{% block carousel %}
{% endblock %}
{% block body %}
    <div class="container" style="padding-top: 60px;">
        <h1 class="page-header">{{ profile.user.username }}</h1>

        <div class="row">
            <!-- left column -->
            <form action="{% url 'users:my' %}" method="post">
                {% csrf_token %}
                <div class="col-md-4 col-sm-6 col-xs-12">
                    <div class="text-center">
                        <img src="{{ profile.photo.url }}" height="400" width="300">
                    </div>
                </div>
                <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
                    <table>
                        <thead>
                        <h3><span class="glyphicon glyphicon-user"></span> <strong>Данные пользователя:</strong></h3>
                        </thead>
                        {% for error in errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                        <br/>
                        <tr>
                            <td><h4><strong>{{ form.first_name.label }} </strong></h4></td>
                            <td>{{ form.first_name }}</td>
                        </tr>
                        <tr>
                            <td><h4><strong>{{ form.last_name.label }} </strong></h4></td>
                            <td>{{ form.last_name }}</td>
                        </tr>
                        <tr>
                            <td><h4><strong>{{ form.gender.label }} </strong></h4></td>
                            <td><h4>{{ form.gender }}</h4></td>
                        </tr>
                        <tr>
                            <td><h4><strong>{{ form.birthday.label }} </strong></h4></td>
                            <td><h4>{{ form.birthday }}</h4></td>
                        </tr>
                        <tr>
                            <td><h4><strong>{{ form.rep_password.label }}</strong></h4></td>
                            <td>{{ form.password }}</td>
                        </tr>
                        <tr>
                            <td><h4><strong>{{ form.password.label }}</strong></h4></td>
                            <td>{{ form.rep_password }}</td>
                        </tr>
                        <tr>
                            <td/>
                            <td><input class="btn btn-lg btn-primary btn-block" type="submit" value="Изменить"/></td>
                        </tr>
                    </table>
                </div>
            </form>
        </div>
    <h4>Питомцы</h4>
    <hr>
    <div class="row">

    </div>
    </div>
{% endblock %}

mysite/users/templates/users/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Профиль
{% endblock %}
{% block css %}
    <link href="{% static 'resources/css/profile.css' %}" rel="stylesheet">
{% endblock %}
{% block carousel %}
{% endblock %}
{% block body %}
    <div class="container" style="padding-top: 60px;">
        <h1 class="page-header">{{ profile.user.username }}</h1>

        <div class="row">
            <!-- left column -->
            <div class="col-md-4 col-sm-6 col-xs-12">
                <div class="text-center">
                    <img src="{{ profile.photo.url }}" height="400" width="300" >
                </div>
            </div>
            <!-- edit form column -->
            <div class="col-md-8 col-sm-6 col-xs-12 personal-info">
                <table>
                    <thead>
                    <h3><strong>Данные пользователя:</strong></h3>
                    </thead>
                    <tr>
                        <td><h4><strong>Имя: </strong></h4></td>
                        <td><h4>{{ profile.user.first_name }}</h4></td>
                    </tr>
                    <tr>
                        <td><h4><strong>Фамилия: </strong></h4></td>
                        <td><h4>{{ profile.user.last_name }}</h4></td>
                    </tr>
                    <tr>
                        <td><h4><strong>Пол: </strong></h4></td>
                        <td><h4>{{ profile.gender }}</h4></td>
                    </tr>
                    <tr>
                        <td><h4><strong>Дата рождения: </strong></h4></td>
                        <td><h4>{{ profile.birthday }}</h4></td>
                    </tr>
                </table>


            </div>
        </div>
    </div>
{% endblock %}

mysite/users/templates/users/registration.html
{% extends 'base.html' %}

{% load staticfiles %}

{% block title %}
    Регистрация
{% endblock %}

{% block css %}
    <link href="{% static 'resources/css/sing_up.css' %}" rel="stylesheet">
{% endblock %}

{% block carousel %}
{% endblock %}

{% block body %}
    <div class="container">
        <form class="form-signup" role="form" action="{% url 'users:registration' %}" method="post"
              enctype="multipart/form-data">
            {% csrf_token %}
            <h2 class="form-signup-heading">Регистрация</h2>
            {% for error in errors %}
                <p>{{ error }}</p>
            {% endfor %}
            {{ form.as_p }}
            <input class="btn btn-lg btn-primary btn-block" type="submit" value="Регистрация"/>
            <a href="{% url 'users:login' %}">Вход</a>
        </form>

    </div>
{% endblock %}

mysite/users/templates/users/success.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}
    Регистрация
{% endblock %}
{% block css %}
    <link href="{% static 'resources/css/success.css' %}" rel="stylesheet">
{% endblock %}
{% block carousel %}
{%  endblock %}
{% block body %}
    <div class="jumbotron">
        <h1>Регистрация прошла успешно</h1>
        <p>В данном сервисе Вы можете завести новых <strong>Питомцов</strong>.</p>
         <p>Или же найти нового хозяйна для питомцев</p>
      </div>
{% endblock %}