mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^pets/', include('pets.urls', namespace='pets')),
    url(r'^news/', include('news.urls', namespace='news')),
    url(r'^shelters/', include('shelters.urls', namespace='shelters')),
    url(r'^$', 'mysite.views.home', name='home'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/news/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^$', 'news.views.show', name='show'),
    url(r'^(?P<id>[0-9]+)/$', 'news.views.details', name='details')
]

mysite/users/urls.py
from django.conf.urls import url

urlpatterns = [
    url(r'^login$', 'users.views.login', name="login"),
    url(r'^logout$', 'users.views.logout', name="logout"),
    url(r'^registration$', 'users.views.register', name='registration'),
    url(r'^(?P<id>[0-9]+)$', 'users.views.profile', name='profile'),
    url(r'my$', 'users.views.my', name='my'),
]

mysite/mysite/views.py
from django.shortcuts import render


# Create your views here.
def home(request):
    return render(request, "base.html", {})

mysite/mysite/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
            Главная
        {% endblock %}
    </title>

    <link href="{% static 'resources/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'resources/css/carousel.css' %}" rel="stylesheet">
    <link href="{% static 'resources/css/footer.css' %}" rel="stylesheet">


    {% block css %}
    {% endblock %}


</head>

<body>


{% block navbar %}
    {% include "navbar.html" %}
{% endblock %}



{% block carousel %}
    {% include "carousel.html" %}
{% endblock %}



{% block body %}
{% endblock %}



{% block footer %}
    <div id="footer">
        <div class="container">
            <p class="text-muted">Django project.</p>
        </div>
    </div>
{% endblock %}


<script src="{% static 'resources/js/jquery.min.js' %}"></script>
<script src="{% static 'resources/js/bootstrap.min.js' %}"></script>


{%  block js %}
{% endblock %}

</body>
</html>

mysite/mysite/templates/carousel.html
<div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
        <li data-target="#carousel-example-generic" data-slide-to="0"></li>
        <li data-target="#carousel-example-generic" data-slide-to="1"></li>
        <li data-target="#carousel-example-generic" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
        <div class="item active">
            <img width="900" src="">
            <div class="carousel-caption">
                <h3>Заголовок1</h3>
                <p>Текст</p>
            </div>
        </div>

        <div class="item">
            <img width="900" src="">
            <div class="carousel-caption">
                <h3>Заголовок2</h3>
                <p>Текст</p>
            </div>
        </div>

        <div class="item">
            <img width="900" src="">
            <div class="carousel-caption">
                <h3>Заголовок3</h3>
                <p>Текст</p>
            </div>
        </div>
    </div>

    <!-- Controls -->
    <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left"></span>
    </a>
    <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right"></span>
    </a>
</div>

mysite/mysite/templates/navbar.html
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <div class="navbar-header">
            <a class="navbar-brand" href="{% url 'home' %}">Питомцы</a>
        </div>
        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'news:show' %}">Новости</a></li>
                <li><a href="{% url 'shelters:show' %}">Приюты</a></li>
                <li><a href="#">Счастливчики</a></li>
                <li><a href="{% url 'users:my' %}">Профиль</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Поиск <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Питомцев</a></li>
                        <li><a href="#">Хозяев</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    <li><a href="{% url 'users:logout' %}?next={{ request.path }}">Выйти <span
                            class="glyphicon glyphicon-log-out"/></a></li>
                {% else %}
                    <li><a href="{% url 'users:login' %}?next={{ request.path }}">Войти <span
                            class="glyphicon glyphicon-log-in"/></a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</div>